/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_vinicius_sticker_domain_libs_ConvertToWebp */

#ifndef _Included_com_vinicius_sticker_domain_libs_ConvertToWebp
#define _Included_com_vinicius_sticker_domain_libs_ConvertToWebp
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_vinicius_sticker_domain_libs_ConvertToWebp
 * Method:    convertToWebp
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_vinicius_sticker_domain_libs_ConvertToWebp_convertToWebp
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
